version: '3'
services:
  apiweb1:
    image: myhttpd:v1
    build: .
    ports:
      - "8090:80"
  apiweb2:
    image: myhttpd:v1
    ports:
      - "8080:80"
  load-balancer:
    image: nginx:latest
    ports:
     - "80:80"
